Cart/urls.py
from django.conf.urls import url

from .views import *
urlpatterns = [
    url(r'^add/$', AddCart, name='AddCart'),
    url(r'^mycart/$', MyCart, name='MyCart'),
    url(r'^mycart/edit/$', EditCart, name='EditCart'),
    url(r'^mycart/checkout/$', Checkout, name='Checkout'),
    url(r'^mycart/checkout/commit/$', CheckoutCommit, name='CheckoutCommit'),
    url(r'^mycart/checkout/payment/$', Payment, name='Payment'),
]

Ecommerce/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete,
    login,
    logout
)
from django.contrib.auth import views as auth_views
from Products.urls import Home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/profile/', Home ),
    url(r'^', Home ),
    url(r'^Products/', include("Products.urls", namespace='Products' )),
    url(r'^Cart/', include("Cart.urls", namespace='Cart' )),
]
#+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cart/models.py
import braintree
from decimal import Decimal
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save, post_save, post_delete
from Products.models import Variation

if settings.DEBUG:

    braintree.Configuration.configure(
        braintree.Environment.Sandbox,
        merchant_id=settings.BRAINTREE_MERCHANT_ID,
        public_key=settings.BRAINTREE_PUBLIC,
        private_key=settings.BRAINTREE_PRIVATE
    )


class CartItem(models.Model):
    cart = models.ForeignKey("Cart", on_delete=models.CASCADE)
    item = models.ForeignKey(Variation, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    line_item_total = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.item.title


def cart_item_pre_save_receiver(sender, instance, *args, **kwargs):
    qty = instance.quantity
    if int(qty) >= 1:
        price = instance.item.get_price()
        line_item_total = Decimal(qty) * Decimal(price)
        instance.line_item_total = line_item_total


pre_save.connect(cart_item_pre_save_receiver, sender=CartItem)


def cart_item_post_save_receiver(sender, instance, *args, **kwargs):
    instance.cart.update_subtotal()


post_save.connect(cart_item_post_save_receiver, sender=CartItem)

post_delete.connect(cart_item_post_save_receiver, sender=CartItem)


class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True)
    items = models.ManyToManyField(Variation, through=CartItem)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    currency = models.CharField(max_length=50, default='Ksh')
    subtotal = models.DecimalField(
        max_digits=50, decimal_places=2, default=0.00)
    total = models.DecimalField(max_digits=50, decimal_places=2, default=0.00)
    # discounts
    # shipping

    def __str__(self):
        return str(self.id)

    def update_subtotal(self):
        print("updating...")
        subtotal = 0
        items = self.cartitem_set.all()
        for item in items:
            subtotal += item.line_item_total
            self.subtotal = "%.2f" % (subtotal)
            self.total = "%.2f" % (subtotal)
            self.save()


class UserCheckout(models.Model):
    Completed = 'Completed'
    Pending = 'Pending'
    Status = (
        (Completed, 'Completed'),
        (Pending, 'Pending')
    )
    stars = models.CharField(max_length=100, choices=Status, default=Pending)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True)
    cart = models.OneToOneField(Cart, unique=True, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    email = models.EmailField()
    phonenumber = models.CharField(max_length=250)
    address1 = models.CharField(max_length=250)
    address2 = models.CharField(max_length=250)
    company = models.CharField(max_length=250)
    country = models.CharField(max_length=250)
    state = models.CharField(max_length=250)
    city = models.CharField(max_length=250)
    zip_code = models.CharField(max_length=250)
    braintree_id = models.CharField(max_length=300, null=True, blank=True)

    def __str__(self):
        return self.first_name+' '+self.last_name

    @property
    def get_braintree_id(self):
        instance = self
        if not instance.braintree_id:
            result = braintree.Customer.create({
                "company": instance.company,
                "email": instance.email,
                "phone": instance.phonenumber,
                "first_name": instance.first_name,
                "last_name": instance.last_name,
            })
            if result.is_success:
                instance.braintree_id = result.customer.id
                instance.save()
        return instance.braintree_id

    def get_client_token(self):
        customer_id = self.get_braintree_id
        if customer_id:

            client_token = braintree.ClientToken.generate({
                'customer_id': customer_id
            })
            return client_token
        return None


def update_braintree_id(sender, instance, *args, **kwargs):
    if not instance.braintree_id:
        instance.get_braintree_id

post_save.connect(update_braintree_id, sender=UserCheckout)

Cart/views.py
import braintree
from django.conf import settings
from django.contrib import messages
from django.http import HttpResponseRedirect, Http404, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect

import json
from django.core import serializers
from .models import *

if settings.DEBUG:

    braintree.Configuration.configure(
        braintree.Environment.Sandbox,
        merchant_id=settings.BRAINTREE_MERCHANT_ID,
        public_key=settings.BRAINTREE_PUBLIC,
        private_key=settings.BRAINTREE_PRIVATE
    )


def AddCart(request):
    if request.is_ajax():
        request.session.set_expiry(0)
        cart_id = request.session.get('cart_id')
        if cart_id == None:
            cart = Cart()
            cart.save()
            cart_id = cart.id
            request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)

        if request.user.is_authenticated():
            print(request.user)
            cart.user = request.user
            cart.save()
        else:
            pass

        item_id = request.POST.get('item')
        delete_item = request.POST.get('delete')
        if item_id:
            item_instance = get_object_or_404(Variation, id=item_id)
            qnt = request.POST.get('qnt')
            cart_item = CartItem.objects.get_or_create(
                cart=cart, item=item_instance)[0]
            if delete_item:
                cart_item.delete()
            else:
                cart_item.quantity = qnt
                cart_item.save()
        messages.success(request, 'Cart Item Saved')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def EditCart(request):
    if request.is_ajax():
        request.session.set_expiry(0)
        cart_id = request.session.get('cart_id')
        cart = Cart.objects.get(id=cart_id)
        post = request.POST
        from_client = request.POST['send']
        from_client = json.loads(from_client)
        for item in from_client:
            vari_id = int(item['id'])
            vari_obj = get_object_or_404(Variation, pk=vari_id)

            cart_item = CartItem.objects.get_or_create(
                cart=cart,
                item=vari_obj
            )
            vari_del = item['del']
            if vari_del == 'True':
                cart_item[0].delete()
            else:
                for key, value in item.items():
                    if key == 'id':
                        pass
                    elif key == 'del':
                        pass
                    elif key == 'qnt':
                        cart_item[0].quantity = value
                        cart_item[0].save()

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def MyCart(request):
    title = 'My Shopping Cart'
    cart_id = request.session.get('cart_id')
    object = get_object_or_404(Cart, pk=cart_id)
    cart_count = object.cartitem_set.count()
    cart_items = object.cartitem_set.all()

    context = {
        'title': title,
        'object': object,
        'cart_count': cart_count,
        'cart_items': cart_items
    }
    return render(request, 'mycart.html', context)


def Checkout(request):
    title = 'Checkout'
    cart_id = request.session.get('cart_id')
    object = get_object_or_404(Cart, pk=cart_id)

    cart_count = object.cartitem_set.count()
    cart_items = object.cartitem_set.all()
    uc = UserCheckout.objects.filter(cart=object)
    if uc:
        return redirect('/Cart/mycart/checkout/payment/')
    context = {
        'title': title,
        'object': object,
        'cart_count': cart_count,
        'cart_items': cart_items
    }
    return render(request, 'checkout.html', context)


def CheckoutCommit(request):
    cart_id = request.session.get('cart_id')
    object = get_object_or_404(Cart, pk=cart_id)

    if request.method == 'POST':
        fname = request.POST.get('firstname')
        lname = request.POST.get('lastname')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        add1 = request.POST.get('address1')
        add2 = request.POST.get('address2')
        comp = request.POST.get('company')
        country = request.POST.get('country')
        state = request.POST.get('state')
        city = request.POST.get('city')
        zcode = request.POST.get('zip')
        user = None

        if request.user.is_authenticated():
            user = request.user
        uc = UserCheckout.objects.filter(cart=object)
        if uc:
            return redirect('/Cart/mycart/checkout/payment/')
        else:
            checkout = UserCheckout.objects.get_or_create(
                user=user,
                cart=object,
                first_name=fname,
                last_name=lname,
                email=email,
                phonenumber=phone,
                address1=add1,
                address2=add2,
                company=comp,
                country=country,
                state=state,
                city=city,
                zip_code=zcode
            )
            print(checkout)
            messages.success(request, 'Details Saved')
            return redirect('/Cart/mycart/checkout/payment/')
    return redirect('/Cart/mycart/checkout/payment/')


def Payment(request):
    title = 'Complete Payment'
    cart_id = request.session.get('cart_id')
    object = get_object_or_404(Cart, pk=cart_id)
    amount = object.total
    cart_count = object.cartitem_set.count()
    cart_items = object.cartitem_set.all()
    checkout_obj = UserCheckout.objects.get(cart=object)
    client_token = checkout_obj.get_client_token()
    context = {
        'title': title,
        'cart_count': cart_count,
        'cart_items': cart_items,
        'checkout_obj': checkout_obj,
        'object': object,
        'client_token': client_token

    }
    if request.method == 'POST':
        nonce = request.POST.get('payment_method_nonce')
        if nonce:
            result = braintree.Transaction.sale({
                "amount": amount,
                "payment_method_nonce": nonce,
                "customer": {

                    "company": checkout_obj.company,
                    "email": checkout_obj.email,
                    "phone": checkout_obj.phonenumber,
                    "first_name": checkout_obj.first_name,
                    "last_name": checkout_obj.last_name,
                },
                "options": {
                    "submit_for_settlement": True
                }
            })
        if result.is_success:
            del request.session["cart_id"]
            checkout_obj.status = 'Completed'
            checkout_obj.save()
            messages.success(
                request, 'Your Payment Been Successfully Completed')
            return redirect('/Products/home/')

        else:
            checkout_obj.status = 'Pending'
            checkout_obj.save()
            messages.success(request, '%s' % (result.message))
            return redirect('/Products/home/')
    return render(request, 'payment.html', context)

Cart/templates/checkout.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<!-- Container -->
<div class="row" style="padding-top:20px;">
  <form action="/Cart/mycart/checkout/commit/" method="post" class="container padding-top-3x padding-bottom-2x">
    {% csrf_token %}
    <h1 class="space-top-half">{{title}}</h1>
    <div class="row padding-top">

      <!-- Checkout Form -->
      <div class="col-sm-8 padding-bottom">
        <div class="row">
          <div class="col-sm-6">
            <input type="text" class="form-control" id="firstname" name="firstname" placeholder="First name" required>
            <input type="email" class="form-control" id="em" name="email" placeholder="Email" required>
            <input type="text" class="form-control" id="add1" name="address1" placeholder="Address 1" required>
          </div>
          <div class="col-sm-6">
            <input type="text" class="form-control" id="lname" name="lastname" placeholder="Last name" required>
            <input type="tel" class="form-control" id="phone" name="phone" placeholder="Phone" required>
            <input type="text" class="form-control" id="add2" name="address2" placeholder="Address 2">
          </div>
        </div><!-- .row -->
        <input type="text" class="form-control" id="co" name="company" placeholder="Company">
        <div class="row">
          <div class="col-sm-6">
            <input type="text" class="form-control" id="county" name="country" placeholder="Country">
            <input type="text" class="form-control" id="ci" name="city" placeholder="City">
          </div>
          <div class="col-sm-6">
            <input type="text" class="form-control" id="state" name="state" placeholder="State">
            <input type="text" class="form-control" id="zip" name="zip" placeholder="ZIP code" required>
          </div>
        </div><!-- .row -->
      </div><!-- .col-sm-8 -->

      <!-- Sidebar -->
      <div class="col-md-3 col-md-offset-1 col-sm-4 padding-bottom">
        <aside>
          <h3>Cart total:</h3>
          <h4>{{object.currency}} {{object.total}}</h4>
          <p class="text-sm text-gray">* Note: This amount includes costs for shipping to address you provided.</p>
          <a href="{% url 'Cart:MyCart' %}" class="btn btn-default btn-ghost icon-left btn-block">
            <i class="material-icons arrow_back"></i>
            Back To Cart
          </a>
          <button id="checkout" type="submit"
            class="btn btn-primary btn-block waves-effect waves-light space-top-none">Checkout</button>
        </aside>
      </div><!-- .col-md-3.col-sm-4 -->
    </div><!-- .row -->
  </form><!-- .container -->
</div>
{% endblock %}

Cart/templates/mycart.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<!-- Container -->
<section class="container padding-top-3x padding-bottom">

  <h1 class="space-top-half">{{title}}</h1>
  <div class="row padding-top">

    <!-- Cart -->
    <div class="col-sm-8 padding-bottom-2x">
      <p class="text-sm">
        <span class="text-gray">Currently</span> {{cart_count}} items
        <span class="text-gray"> in cart</span>
      </p>
      <div class="shopping-cart">
        <!-- Item -->
        {% for i in object.cartitem_set.all %}
        <div class="item">
          <a href="{{i.item.get_absolute_url}}" class="item-thumb">
            {% if i.item.image %}
            <img src="{{i.item.image.url}}" alt="Product">
            {% else %}
            <img src="{% static 'img/default/1.png' %}" alt="Shop item">
            {% endif %}
          </a>
          <div class="item-details">
            <h3 class="item-title"><a href="{{i.item.get_absolute_url}}">{{i.item.product}}-
                <small>{{ i.item.title }}</small></a></h3>
            <h4 class="item-price sitem" data-pr="{{i.item.get_price}}">{{object.currency}} {{ i.line_item_total }}</h4>
            <div class="count-input">
              <a class="incr-btn" data-action="decrease" href="#">–</a>
              <input id="{{i.item.pk}}" class="quantity" type="text" value="{{i.quantity}}"
                data-p="{{i.item.get_price}}">
              <a class="incr-btn" data-action="increase" href="#">+</a>
            </div>
          </div>
          <a href="#" class="item-remove" data-toggle="tooltip" data-placement="top" title="Remove" data-delete="False">
            <i class="material-icons remove_shopping_cart"></i>
          </a>
        </div><!-- .item -->
        {% endfor %}
      </div><!-- .shopping-cart -->
      <!-- Coupon -->
    </div><!-- .col-sm-8 -->

    <!-- Sidebar -->
    <div class="col-md-3 col-md-offset-1 col-sm-4 padding-bottom-2x">
      <aside>
        <h3 class="toolbar-title">Cart subtotal:</h3>
        <h4 id="total" class="amount">{{object.currency}} {{object.total}}</h4>
        <p class="text-sm text-gray">* Note: This amount does not include costs for international shipping. You will be
          able to calculate shipping costs on checkout.</p>
        <a href="#" class="btn btn-default btn-block waves-effect waves-light update">Update Cart</a>
        <a href="{% url 'Cart:Checkout' %}"
          class="btn btn-primary btn-block waves-effect waves-light space-top-none">Checkout</a>
      </aside>
    </div><!-- .col-md-3.col-sm-4 -->
  </div><!-- .row -->
</section><!-- .container -->

{% endblock %}

Cart/templates/payment.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<!-- Container -->
<div class="row" style="padding-top:20px;">
  <form action="." method="post" class="container padding-top-3x padding-bottom-2x">{% csrf_token %}
    <div class="row ">

      <!-- Checkout Form -->
      <div class="col-sm-7 padding-bottom">
        <div class="row">
          <div class="col-sm-7">
            <h2>Ecommerce Company</h2>
          </div>
          <div class="col-sm-5">
            <ul style="list-style:none;">
              <li><i style="color:#77cde3;" class="material-icons">email</i> test@gmail.com</li>
              <li><i style="color:#77cde3;" class="material-icons">phone</i> +254 708 808 521</li>
              <li><i style="color:#77cde3;" class="material-icons">contact_phone</i> +254 708 808 521</li>
              <li><i class="material-icons" style="color:#77cde3;">pin_drop</i> My place is here</li>
              <li>zipcode: 02342332</li>
            </ul>
          </div>
        </div><!-- .row -->
        <h5 style="color:#77cde3;">Order Summary</h5>
        <hr>
        <div class="row">
          <div class="col-sm-12">
            <table class="table">
              <thead>
                <tr>
                  <th>No#</th>
                  <th width="10%" height="8%;">Image</th>
                  <th>Product</th>
                  <th>Price</th>
                  <th>Qnt</th>
                  <th>Amount</th>
                </tr>
              </thead>
              <tbody>
                {% for i in cart_items  %}
                <tr>
                  <th scope="row">{{forloop.counter}}</th>

                  <td>
                    {% if i.item.image %}
                    <img src="{{i.item.image.url}}" alt="Product">
                    {% else %}
                    <img src="{% static 'img/default/1.png' %}" alt="Shop item">
                    {% endif %}
                  </td>
                  <td>{{i.item.product}}({{i.item}})</td>
                  <td> {{cart.currency}} {{i.item.get_price}}</td>
                  <td>{{i.quantity}}</td>
                  <td>{{i.line_item_total}}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-5 col-sm-offset-7" style="text-align:right;">
            <h4>Total </h4> {{object.currency}} <small style="color:#77cde3;">{{object.total}}</small>
          </div>
        </div>

      </div><!-- .col-sm-8 -->

      <!-- Sidebar -->
      <div class="col-md-4 col-md-offset-1 col-sm-4 padding-bottom">
        <aside>
          <h3>Cart total: {{object.currency}} <small style="color:#77cde3;">{{object.total}}</small></h3>
          <p class="text-sm text-gray">* Note: This amount includes costs for shipping to address you provided.</p>

          <form id="checkout" action="." method="post" enctype="multipart/form-data">{% csrf_token %}
            <div id="payment-form"></div><br>
            <button id="payment" type="submit"
              class="btn btn-primary btn-block waves-effect waves-light space-top-none">Pay</button>
          </form>
          <a href="{% url 'Cart:MyCart' %}" class="btn btn-default btn-ghost icon-left btn-block">
            <i class="material-icons arrow_back"></i>
            Back To Cart
          </a>

        </aside>
      </div><!-- .col-md-3.col-sm-4 -->
    </div><!-- .row -->
  </form><!-- .container -->
</div>
<script type="text/javascript">
  var clientToken = "{{client_token}}";
  braintree.setup(clientToken, "dropin", {
    container: "payment-form"
  });
</script>
{% endblock %}